export const GET_ALL_FORUMS = 'GET_ALL_FORUMS';

export const GET_UNPINNED_THREADS_START = 'GET_UNPINNED_THREADS_START';
export const GET_UNPINNED_THREADS_SUCCESS = 'GET_UNPINNED_THREADS_SUCCESS';
export const GET_UNPINNED_THREADS_FAILED = 'GET_UNPINNED_THREADS_FAILED';

export const GET_PINNED_THREADS_START = 'GET_PINNED_THREADS_START';
export const GET_PINNED_THREADS_SUCCESS = 'GET_PINNED_THREADS_SUCCESS';
export const GET_PINNED_THREADS_FAILED = 'GET_PINNED_THREADS_FAILED';

export const GET_THREAD_START = 'GET_THREAD_START';
export const GET_THREAD_SUCCESS = 'GET_THREAD_SUCCESS';
export const GET_THREAD_FAILED = 'GET_THREAD_FAILED';

export const GET_REPLIES_START = 'GET_REPLIES_START';
export const GET_REPLIES_SUCCESS = 'GET_REPLIES_SUCCESS';
export const GET_REPLIES_FAILED = 'GET_REPLIES_FAILED';

export const CREATE_THREAD_START = 'CREATE_THREAD_START';
export const CREATE_THREAD_SUCCESS = 'CREATE_THREAD_SUCCESS';
export const CREATE_THREAD_FAILED = 'CREATE_THREAD_FAILED';

export const SET_CURRENT_THREAD = 'SET_CURRENT_THREAD';

export const CREATE_REPLY_START = 'CREATE_REPLY_START';
export const CREATE_REPLY_SUCCESS = 'CREATE_REPLY_SUCCESS';
export const CREATE_REPLY_FAILED = 'CREATE_REPLY_FAILED';

export const SET_THREAD_FAVORITES = 'SET_THREAD_FAVORITES';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';

export const GET_USER_THREADS_START = 'GET_USER_THREADS_START';
export const GET_USER_THREADS_SUCCESS = 'GET_USER_THREADS_SUCCESS';
export const GET_USER_THREADS_FAILED = 'GET_USER_THREADS_FAILED';

export const DELETE_THREAD_START = 'DELETE_THREAD_START';
export const DELETE_THREAD_SUCCESS = 'DELETE_THREAD_SUCCESS';
export const DELETE_THREAD_FAILED = 'DELETE_THREAD_FAILED';
