export const GET_ALL_FORUMS = 'GET_ALL_FORUMS';

export const CLEAR_UNPINNED_THREADS = 'CLEAR_UNPINNED_THREADS';
export const GET_UNPINNED_THREADS_FOR_FORUM = 'GET_UNPINNED_THREADS_FOR_FORUM';

export const CLEAR_PINNED_THREADS = 'CLEAR_PINNED_THREADS';
export const GET_PINNED_THREADS_FOR_FORUM = 'GET_PINNED_THREADS_FOR_FORUM';

export const GET_THREAD_START = 'GET_THREAD_START';
export const GET_THREAD_SUCCESS = 'GET_THREAD_SUCCESS';
export const GET_THREAD_FAILED = 'GET_THREAD_FAILED';

export const GET_REPLIES_FOR_THREAD = 'GET_REPLIES_FOR_THREAD';
export const SET_CURRENT_THREAD = 'SET_CURRENT_THREAD';
export const CREATE_REPLY = 'CREATE_REPLY';
export const SET_THREAD_FAVORITES = 'SET_THREAD_FAVORITES';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';

export const CLEAR_USER_THREADS = 'CLEAR_USER_THREADS';
export const GET_USER_THREADS = 'GET_USER_THREADS';

export const DELETE_THREAD_START = 'DELETE_THREAD_START';
export const DELETE_THREAD_SUCCESS = 'DELETE_THREAD_SUCCESS';
export const DELETE_THREAD_FAILED = 'DELETE_THREAD_FAILED';
export const DELETE_THREAD_REDIRECT = 'DELETE_THREAD_REDIRECT';
