export const GET_ALL_FORUMS_START = 'GET_ALL_FORUMS_START';
export const GET_ALL_FORUMS_SUCCESS = 'GET_ALL_FORUMS_SUCCESS';
export const GET_ALL_FORUMS_FAILED = 'GET_ALL_FORUMS_FAILED';

export const CREATE_FORUM_START = 'CREATE_FORUM_START';
export const CREATE_FORUM_SUCCESS = 'CREATE_FORUM_SUCCESS';
export const CREATE_FORUM_FAILED = 'CREATE_FORUM_FAILED';
export const CREATE_FORUM_RESET = 'CREATE_FORUM_RESET';

export const DELETE_FORUM_START = 'DELETE_FORUM_START';
export const DELETE_FORUM_SUCCESS = 'DELETE_FORUM_SUCCESS';
export const DELETE_FORUM_FAILED = 'DELETE_FORUM_FAILED';

export const GET_UNPINNED_THREADS_START = 'GET_UNPINNED_THREADS_START';
export const GET_UNPINNED_THREADS_SUCCESS = 'GET_UNPINNED_THREADS_SUCCESS';
export const GET_UNPINNED_THREADS_FAILED = 'GET_UNPINNED_THREADS_FAILED';

export const GET_PINNED_THREADS_START = 'GET_PINNED_THREADS_START';
export const GET_PINNED_THREADS_SUCCESS = 'GET_PINNED_THREADS_SUCCESS';
export const GET_PINNED_THREADS_FAILED = 'GET_PINNED_THREADS_FAILED';

export const GET_USER_PROFILE_START = 'GET_USER_PROFILE_START';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILED = 'GET_USER_PROFILE_FAILED';

export const GET_USER_THREADS_START = 'GET_USER_THREADS_START';
export const GET_USER_THREADS_SUCCESS = 'GET_USER_THREADS_SUCCESS';
export const GET_USER_THREADS_FAILED = 'GET_USER_THREADS_FAILED';
