export const GET_THREAD_START = 'GET_THREAD_START';
export const GET_THREAD_SUCCESS = 'GET_THREAD_SUCCESS';
export const GET_THREAD_FAILED = 'GET_THREAD_FAILED';

export const CREATE_THREAD_START = 'CREATE_THREAD_START';
export const CREATE_THREAD_SUCCESS = 'CREATE_THREAD_SUCCESS';
export const CREATE_THREAD_FAILED = 'CREATE_THREAD_FAILED';

export const DELETE_THREAD_START = 'DELETE_THREAD_START';
export const DELETE_THREAD_SUCCESS = 'DELETE_THREAD_SUCCESS';
export const DELETE_THREAD_FAILED = 'DELETE_THREAD_FAILED';

export const SET_CURRENT_THREAD = 'SET_CURRENT_THREAD';

export const GET_REPLIES_START = 'GET_REPLIES_START';
export const GET_REPLIES_SUCCESS = 'GET_REPLIES_SUCCESS';
export const GET_REPLIES_FAILED = 'GET_REPLIES_FAILED';

export const CREATE_REPLY_START = 'CREATE_REPLY_START';
export const CREATE_REPLY_SUCCESS = 'CREATE_REPLY_SUCCESS';
export const CREATE_REPLY_FAILED = 'CREATE_REPLY_FAILED';
export const CREATE_THREAD_RESET = 'CREATE_THREAD_RESET';

export const DELETE_REPLY_START = 'DELETE_REPLY_START';
export const DELETE_REPLY_SUCCESS = 'DELETE_REPLY_SUCCESS';
export const DELETE_REPLY_FAILED = 'DELETE_REPLY_FAILED';

export const SET_THREAD_FAVORITES_START = 'SET_THREAD_FAVORITES_START';
export const SET_THREAD_FAVORITES_SUCCESS = 'SET_THREAD_FAVORITES_SUCCESS';
export const SET_THREAD_FAVORITES_FAILED = 'SET_THREAD_FAVORITES_FAILED';

export const SET_PINNED_STATUS_START = 'SET_PINNED_STATUS_START';
export const SET_PINNED_STATUS_SUCCESS = 'SET_PINNED_STATUS_SUCCESS';
export const SET_PINNED_STATUS_FAILED = 'SET_PINNED_STATUS_FAILED';

export const THREAD_ERRORS_RESET = 'THREAD_ERRORS_RESET';
